
general.import = ["colors/onedark_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[window]
#decorations = "none"
padding = { x = 4, y = 4 }
