#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.50

bspc config single_monocle        true
bspc config gapless_monocle       true
bspc config borderless_monocle    true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
