#! /bin/sh

setxkbmap -layout us,ara -variant ,digits -option grp:alt_shift_toggle caps:escape &
feh --bg-fill $HOME/.config/wallpaper.jpg &
sxhkd &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio             0.50
bspc config single_monocle          true
bspc config gapless_monocle         true
bspc config borderless_monocle      true
bspc config pointer_follows_focus   true
bspc config focus_follows_pointer   true
