#! /bin/sh

sxhkd &
xrandr --rate 144 &
feh --bg-fill --randomize $HOME/personal/wallpapers/* &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap           0
bspc config split_ratio          0.5

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
